name: CI Pipeline

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main','dev' ]

env:
  REGISTRY: ghcr.io
  REPOSITORY_NAME: ${{ github.repository }}

jobs:
  build:
    name: 'Build Package'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Build Package
        uses: casperdcl/deploy-pypi@v2
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          gpg_key: $ {{ secrets.GPG_KEY }}
          pip: true
          upload: false

  create-release:
    name: 'Create Release'
    needs: [ build ]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Get Version from Commit History
        uses: mathieudutour/github-tag-action@v6.0
        id: tag_version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          pre_release_branches: dev
      - name: Write Version to File
        run: |
          echo "${{ steps.tag_version.outputs.new_tag }}" > .VERSION
      - uses: actions/setup-python@v2
      - name: Build Package
        uses: casperdcl/deploy-pypi@v2
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          gpg_key: ${{ secrets.GPG_KEY }}
          pip: true
          upload: true
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
